export enum EducationalLevel {
  NONE = 'NONE',
  ELEMENTARY_SCHOOL = 'PRIMARY_SCHOOL',
  SECONDARY_SCHOOL = 'SECONDARY_SCHOOL',
  HIGH_SCHOOL_GRADUATE = 'HIGH_SCHOOL_GRADUATE',
  ASSOCIATE_DEGREE = 'ASSOCIATE_DEGREE',
  BACHELOR_DEGREE = 'BACHELOR_DEGREE',
  MASTER_DEGREE = 'MASTER_DEGREE', 
  DOCTORATE = 'DOCTORATE',
  OTHER = 'OTHER',
}